server:
  tomcat:
    max-part-count: 50
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/vetlog
    username: ${USER}
    password: ${PASSWORD}
    driverClassName: com.mysql.jdbc.Driver
    maxActive:  50
    maxIdle: 5
    minIdle: 25
    initialSize: 10
    validationQuery: SELECT 1
    testOnBorrow: true
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    maxWait: 10000
    template:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    include: development
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  cloud:
    gcp:
      projectId: vetlog-357216
      core:
        enabled: true
      credentials:
        location: classpath:vetlog.json
  flyway:
    baseline-on-migrate: true
message: Hello Vetlog!
gmailer:
  url: https://gmailer.josdem.io/emailer/
  path: message
baseUrl: https://vetlog.org/
template:
  forgot:
    name: forgotPassword.ftl
    path: recovery/forgot/
  adoption:
    name: adoption.ftl
  welcome: welcome.ftl
breedsByTypeUrl: http://localhost:8080/breed/list
imageBucket: vetlog-bucket
prescriptionBucket: prescription-bucket
gcpUrl: https://storage.googleapis.com/
defaultImage: default-image.png
token: userToken
geoToken: userToken
veterinarians:
  - "vet-1"
  - "vet-2"
countryCodes:
  - "+countryCodeOne"
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
google:
  url: "https://www.googleapis.com/geolocation/v1/"
  apiKey: ${GOOGLE_API_KEY}
backend:
  url: "https://vetlog-backend.josdem.io/geolocation/"
  token: "c01ac30d-f047-40a9-9ee9-fb94d9de9577"
geolocation:
  latitude: 19.376699
  longitude: -99.211900